import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { Sidebar } from "@/components/global/sidebar";
import { Navbar } from "@/components/global/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NEOSYNC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
          {/* Sidebar */}
          <Sidebar />
          {/* Main content area */}
          <div className="flex flex-col">
            {/* Navbar */}
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
